# Generated by Django 4.1.3 on 2023-01-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration): 

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='', max_length=122)),
                ('lastName', models.CharField(default='', max_length=122)),
                ('username', models.CharField(default='', max_length=122)),
                ('email', models.CharField(default='', max_length=122)),
                ('address', models.TextField(default='')),
                ('address2', models.TextField(default='')),
                ('ccname', models.CharField(default='', max_length=122)),
                ('ccnumber', models.IntegerField(default=0)),
                ('ccexpiration', models.TextField(default='')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
