# Generated by Django 4.1.3 on 2023-01-23 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_contact_phone'),
        ('Home', '0008_billing'),
    ]

    operations = [
    ]
