# Generated by Django 4.1.3 on 2023-01-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_alter_contact_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=122)),
                ('phone', models.IntegerField()),
                ('uname', models.CharField(max_length=122)),
                ('psw', models.CharField(max_length=122)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
